---
- name: devops training
  hosts: devops
  tasks:
    - name: Show a hello world message
      debug:
        msg: "Hello world !"

    - name: Create a file
      file:
        path: /tmp/devops.txt
        state: touch
        owner: ansible
        mode: 0644
...
